# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-01 05:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accountsettings',
            options={'verbose_name_plural': 'settings'},
        ),
        migrations.RemoveField(
            model_name='clock',
            name='id',
        ),
        migrations.AddField(
            model_name='clock',
            name='clock_id',
            field=models.AutoField(default=10, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
