# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-01 05:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0002_auto_20170701_0028'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='clock',
            unique_together=set([('owner', 'arrIndex')]),
        ),
    ]
