# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-02 02:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20170701_0032'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='placeid',
            new_name='place_id',
        ),
    ]
