# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-09 00:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20170701_2115'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='clock',
            unique_together=set([]),
        ),
    ]
