# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-09 01:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20170708_1928'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clock',
            name='metric',
        ),
    ]
